Repository bcgov/digital-journeys, pull requests merged in 2022-02, with the labels that each got.

#59 DGJ-11 Added scripts to run the project locally
  .gitignore
  Makefile
  docker-compose.yml
  forms-flow-api/Dockerfile
  forms-flow-bpm/Dockerfile
  forms-flow-bpm/pom-docker.xml
  forms-flow-bpm/pom.xml
  forms-flow-bpm/settings-docker.xml
  forms-flow-bpm/src/main/test.txt
  forms-flow-bpm/target/forms-flow-bpm.jar
  forms-flow-bpm/target/forms-flow-bpm.jar.original
  forms-flow-bpm/target/maven-archiver/pom.properties
  forms-flow-forms/Dockerfile
  forms-flow-forms/package-lock.json
  forms-flow-forms/package.json
  forms-flow-web/Dockerfile
  forms-flow-web/Dockerfile.prod
  forms-flow-web/lsyncd.conf
  forms-flow-web/package-lock.json
  forms-flow-web/package.json
  forms-flow-web/public/logo.svg
  forms-flow-web/src/index.js
  forms-flow-web/src/styles.scss
  wait-for-it.sh
Labels: Development

#67 DGJ-62 Apply DGJ changes on top of formsflow repo
  forms-flow-web/Dockerfile.prod
Labels: Development

#88 Remove IMAGE_NAME and IMAGE_TAG parameters
  .github/workflows/deploy.yaml
Labels: Development, devops

#92 Format the Json string for react permisssions in config map
  deployment/openshift/web_dc.yaml
Labels: devops

#98 using user data multiple time in a form improved to the forms with ne…
  forms-flow-api/src/formsflow_api/models/employee_data.py
  forms-flow-web/src/components/Form/Item/View.js
Labels: Development
